/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include "s21_matrix.h"

START_TEST(error1) {
#line 4
  matrix_t A;
  int rows = 0;
  int columns = -5;
  int return_value;
  return_value = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(error2) {
#line 12
  matrix_t A;
  int rows = 1;
  int columns = 1;
  int return_value;
  return_value = s21_create_matrix(rows, columns, &A);
  ck_assert_int_eq(return_value, OK);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(eq1) {
#line 21
  matrix_t A;
  matrix_t B;
  make_triangle_matrix(3, 3, &A);
  make_triangle_matrix(3, 3, &B);
  ck_assert_int_eq(s21_eq_matrix(&A, &B), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq2) {
#line 30
  matrix_t A;
  matrix_t B;
  make_triangle_matrix(2, 3, &A);
  make_triangle_matrix(4, 3, &B);
  ck_assert_int_eq(s21_eq_matrix(&A, &B), FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq4) {
#line 39
  matrix_t A, B;
  s21_create_matrix(1, 1, &A);
  s21_create_matrix(1, 1, &B);

  A.matrix[0][0] = 1.2500005;
  B.matrix[0][0] = 2.2500005;

  ck_assert_int_eq(s21_eq_matrix(&A, &B), 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq5) {
#line 51
  int return_value = s21_eq_matrix(NULL, NULL);
  ck_assert_int_eq(return_value, FAILURE);
}
END_TEST

START_TEST(sum1) {
#line 55
  matrix_t A;
  matrix_t B;
  matrix_t C;
  matrix_t result;
  make_triangle_matrix(3, 3, &A);
  make_triangle_matrix(3, 4, &B);
  make_triangle_matrix(3, 7, &C);
  s21_sum_matrix(&A, &B, &result);
  int return_value = s21_eq_matrix(&result, &C);
  ck_assert_int_eq(SUCCESS, return_value);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(sum2) {
#line 71
  matrix_t A;
  matrix_t B;
  make_triangle_matrix(2, 4, &A);
  make_triangle_matrix(3, 4, &B);
  matrix_t res;
  int return_value = s21_sum_matrix(&A, &B, &res);
  ck_assert_int_eq(return_value, CALC_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(sum3) {
#line 82
  int return_value = s21_sum_matrix(NULL, NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(sub1) {
#line 86
  matrix_t A;
  matrix_t B;
  matrix_t C;
  matrix_t result;
  make_triangle_matrix(3, 3, &A);
  make_triangle_matrix(3, 4, &B);
  make_triangle_matrix(3, -1, &C);
  s21_sub_matrix(&A, &B, &result);
  int return_value = s21_eq_matrix(&result, &C);
  ck_assert_int_eq(SUCCESS, return_value);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(sub2) {
#line 102
  matrix_t A;
  matrix_t B;
  make_triangle_matrix(2, 4, &A);
  make_triangle_matrix(3, 4, &B);
  matrix_t res;
  int return_value = s21_sub_matrix(&A, &B, &res);
  ck_assert_int_eq(return_value, CALC_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(sub3) {
#line 113
  int return_value = s21_sub_matrix(NULL, NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(mult_num1) {
#line 117
  matrix_t A;
  matrix_t C;
  matrix_t res;
  make_triangle_matrix(2, 2, &A);
  double B = 3;
  make_triangle_matrix(2, 6, &C);
  int return_value = s21_mult_number(&A, B, &res);
  return_value = s21_eq_matrix(&res, &C);
  ck_assert_int_eq(return_value, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&C);
}
END_TEST

START_TEST(mult_num2) {
#line 131
  int return_value = s21_mult_number(NULL, 3, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(mult1) {
#line 135
  matrix_t A;
  matrix_t C;
  matrix_t res;
  make_triangle_matrix(3, 2, &A);
  matrix_t B;
  s21_create_matrix(3, 3, &C);
  C.matrix[0][0] = 6;
  C.matrix[0][1] = 12;
  C.matrix[0][2] = 18;
  C.matrix[1][0] = 0;
  C.matrix[1][1] = 6;
  C.matrix[1][2] = 12;
  C.matrix[2][0] = 0;
  C.matrix[2][1] = 0;
  C.matrix[2][2] = 6;
  make_triangle_matrix(3, 3, &B);
  s21_mult_matrix(&A, &B, &res);
  int return_value = s21_eq_matrix(&res, &C);
  ck_assert_int_eq(return_value, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&C);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(mult2) {
#line 160
  matrix_t A;
  matrix_t res;
  make_triangle_matrix(3, 2, &A);
  matrix_t B;
  make_triangle_matrix(2, 3, &B);
  int return_value = s21_mult_matrix(&A, &B, &res);
  ck_assert_int_eq(return_value, CALC_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(mult3) {
#line 171
  int return_value = s21_mult_matrix(NULL, NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(transp1) {
#line 175
  matrix_t A;
  matrix_t res;
  matrix_t C;
  make_triangle_matrix(3, 2, &A);
  make_low_triangle_matrix(3, 2, &C);
  int return_value = s21_transpose(&A, &res);
  return_value = s21_eq_matrix(&res, &C);
  ck_assert_int_eq(return_value, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(transp2) {
#line 188
  int return_value = s21_transpose(NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(calc1) {
#line 192
  matrix_t A;
  matrix_t C;
  matrix_t res;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[0][2] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 1;
  A.matrix[1][2] = 1;
  A.matrix[2][0] = 1;
  A.matrix[2][1] = 1;
  A.matrix[2][2] = 3;
  s21_create_matrix(3, 3, &C);
  C.matrix[0][0] = 2;
  C.matrix[0][1] = -2;
  C.matrix[0][2] = 0;
  C.matrix[1][0] = -5;
  C.matrix[1][1] = 2;
  C.matrix[1][2] = 1;
  C.matrix[2][0] = 1;
  C.matrix[2][1] = 0;
  C.matrix[2][2] = -1;
  s21_calc_complements(&A, &res);
  int return_value = s21_eq_matrix(&C, &res);
  ck_assert_int_eq(SUCCESS, return_value);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&C);
}
END_TEST

START_TEST(calc2) {
#line 223
  matrix_t A;
  matrix_t res;
  s21_create_matrix(1, 2, &A);
  int return_value = s21_calc_complements(&A, &res);
  ck_assert_int_eq(return_value, CALC_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(calc3) {
#line 231
  int return_value = s21_calc_complements(NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(determ1) {
#line 235
  matrix_t A;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  A.matrix[0][2] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 1;
  A.matrix[1][2] = 1;
  A.matrix[2][0] = 1;
  A.matrix[2][1] = 1;
  A.matrix[2][2] = 1;
  double b;
  s21_determinant(&A, &b);
  double res = 0;
  ck_assert_double_eq_tol(res, b, 1e-7);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determ2) {
#line 253
  int return_value = s21_determinant(NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(determ3) {
#line 257
  matrix_t A;
  double b;
  s21_create_matrix(2, 4, &A);
  int return_value = s21_determinant(&A, &b);
  ck_assert_int_eq(return_value, CALC_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determ4) {
#line 265
  matrix_t A;
  double b;
  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 2;
  s21_determinant(&A, &b);
  ck_assert_double_eq_tol(b, 2, 1e-7);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(inv1) {
#line 274
  matrix_t A;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 1;
  A.matrix[0][2] = 1;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 1;
  A.matrix[1][2] = 1;
  A.matrix[2][0] = 1;
  A.matrix[2][1] = 1;
  A.matrix[2][2] = 1;
  matrix_t res;
  int return_value = s21_inverse_matrix(&A, &res);
  ck_assert_int_eq(return_value, CALC_ERROR);
}
END_TEST

START_TEST(inv2) {
#line 290
  matrix_t A;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 6;
  A.matrix[0][2] = 9;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 1;
  A.matrix[1][2] = 6;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 0;
  A.matrix[2][2] = 1;
  matrix_t res;
  int return_value = s21_inverse_matrix(&A, &res);
  matrix_t C;
  s21_create_matrix(3, 3, &C);
  C.matrix[0][0] = 1;
  C.matrix[0][1] = -6;
  C.matrix[0][2] = 27;
  C.matrix[1][0] = 0.0;
  C.matrix[1][1] = 1;
  C.matrix[1][2] = -6;
  C.matrix[2][0] = 0;
  C.matrix[2][1] = 0.0;
  C.matrix[2][2] = 1;
  return_value = s21_eq_matrix(&res, &C);
  ck_assert_int_eq(return_value, SUCCESS);
  s21_remove_matrix(&C);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(inv3) {
#line 321
  int return_value = s21_inverse_matrix(NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

START_TEST(inv4) {
#line 325
  int return_value = s21_inverse_matrix(NULL, NULL);
  ck_assert_int_eq(return_value, INCORRECT_MATRIX);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, error1);
  tcase_add_test(tc1_1, error2);
  tcase_add_test(tc1_1, eq1);
  tcase_add_test(tc1_1, eq2);
  tcase_add_test(tc1_1, eq4);
  tcase_add_test(tc1_1, eq5);
  tcase_add_test(tc1_1, sum1);
  tcase_add_test(tc1_1, sum2);
  tcase_add_test(tc1_1, sum3);
  tcase_add_test(tc1_1, sub1);
  tcase_add_test(tc1_1, sub2);
  tcase_add_test(tc1_1, sub3);
  tcase_add_test(tc1_1, mult_num1);
  tcase_add_test(tc1_1, mult_num2);
  tcase_add_test(tc1_1, mult1);
  tcase_add_test(tc1_1, mult2);
  tcase_add_test(tc1_1, mult3);
  tcase_add_test(tc1_1, transp1);
  tcase_add_test(tc1_1, transp2);
  tcase_add_test(tc1_1, calc1);
  tcase_add_test(tc1_1, calc2);
  tcase_add_test(tc1_1, calc3);
  tcase_add_test(tc1_1, determ1);
  tcase_add_test(tc1_1, determ2);
  tcase_add_test(tc1_1, determ3);
  tcase_add_test(tc1_1, determ4);
  tcase_add_test(tc1_1, inv1);
  tcase_add_test(tc1_1, inv2);
  tcase_add_test(tc1_1, inv3);
  tcase_add_test(tc1_1, inv4);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
